<b><h2 style="text-align:center";><font 
color='#a8a6ab'>𝐑</font><font 
color='#a8a6ab'>𝐨</font><font 
color='#a8a6ab'>𝐳</font><font
color='#a8a6ab'>𝐳</font><font 
color='#a8a6ab'> </font><font 
color='#a8a6ab'>𝐒</font><font 
color='#a8a6ab'>𝐓</font><font    
color='#a8a6ab'>𝐎</font><font
color='#a8a6ab'>𝐑</font><font
color='#a8a6ab'>𝐄</font><font
color='#00FF1D'> </font><font 
color='#FFCC00'>𝐓</font><font 
color='#FFCC00'>𝐮</font><font 
color='#FFCC00'>𝐧</font><font 
color='#FFCC00'>𝐧</font><font 
color='#FFCC00'>𝐞</font><font 
color='#FFCC00'>𝐥</font><font  
color='#FFCC00'></font></b><br><br>
<b><h2 style="text-align:center";><font 
<font color="white">Telegram: t.me/roz_zero</font><br>
<font color="white">WhatsApp : wa.me/6282120919842</font><br>
